# Generated by Django 5.2.3 on 2025-08-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('historia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('posicao', models.CharField(choices=[('GK', 'Goleiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('ZAG', 'Zagueiro'), ('VOL', 'Volante'), ('MD', 'Meia Direita'), ('ME', 'Meia Esquerda'), ('MC', 'Meia Central'), ('MAT', 'Meia Atacante'), ('AD', 'Ala Direito'), ('AE', 'Ala Esquerdo'), ('PD', 'Ponta Direita'), ('PE', 'Ponta Esquerda'), ('SA', 'Segundo Atacante'), ('CA', 'Centroavante')], max_length=20)),
                ('idade', models.IntegerField()),
                ('dt_nasc', models.DateField()),
                ('imagem', models.ImageField(upload_to='jogadores-elenco/')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('criador', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.ImageField(upload_to='bandeira-time/')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.PositiveSmallIntegerField()),
                ('gols_visitante', models.PositiveSmallIntegerField()),
                ('competicao', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('artilheiro', models.CharField(max_length=100)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='app.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='app.time')),
            ],
        ),
    ]
